### ISSUE TITLE
404 Bad Request: invalid value for idList 

### ISSUE THREAD

**Issue by MXKhronos** [HypheX/trello-v1#2]
Found an issue when attempting to create a new card on a list. I tested the POST url with Postman and got this. I was replied from the post request with `invalid value for idList` so I changed `idCard` with `idList` and it worked in Main.lua

return (ConList.Card.new({name = name, ~~idCard~~idList = parent:GetId()}, ConList["Board"], ConList["List"], ConList["Card"]))

**Comment by LFS6502** [comment]
Aye, thank you. I made a typo there. I'll release this as 1.1.2
