### ISSUE TITLE
Card:GetComments()

### ISSUE THREAD

**Issue by MXKhronos** [HypheX/trello-v1#3]
Hello, I'm working on a "Contact Support" feature for my game and I want to use the Trello Card's comments section as a support chat room.

If it's possible to add a function to return a table of Comment objects sorted by time posted that would be insanely useful.

**ADD
I have found that some comments are location inside the `actions` JSON object, and maybe the function could go through them and get `type == "commentCard"` then sort by `date` if it's not already sorted. Hope this helps!

**ADD
While I was working, I got this working. If you like, you can add it into the API. I believe it's already sorted by latest to oldest.
```
function NewCard:GetActions(filter)
	local JSON
	pcall(function()
		JSON = HTTP:GetAsync("https://api.trello.com/1/cards/"..self:GetId().."/actions"..(filter and "?filter="..filter.."&"..auth:sub(2, #auth) or auth))
	end)
	return (HTTP:JSONDecode(JSON))
end
		
function NewCard:GetComments()
	return self:GetActions("commentCard");
end
```

Thanks for this API again!

**Comment by LFS6502** [comment]
Oh crap! I forgot to check issues! I am sorry.

I am in fact going to add this feature, though, I need to add a Label object first.

**Comment by LFS6502** [comment]
Closing this issue as I'll be rewriting the API, 2.0.0 is coming.
